version: 0.2

phases:
  install:
    commands:
      - composer install -n --no-dev --prefer-dist --working-dir=./server/
      - cd server/; npm ci

  build:
    commands:
      - cd server/; npm run prod

artifacts:
  files:
    - './**/*'
