version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./server/
      - save_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
          paths: ./server/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "./server/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d ./server/node_modules ]; then
              cd server/; npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "./server/package-lock.json }}
          paths:
            - ./server/node_modules
      - run: cd server/; npm run dev
      # - run: cd server/; php artisan migrate --force
      # - run: cd server/; php artisan db:seed --force
