version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist --working-dir=./server/
      - run: cd server/; npm ci
      - run: cd server/; npm run dev
      # - run: cd server/; php artisan migrate --force
      # - run: cd server/; php artisan db:seed --force
