version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./server/
      - save_cache:
          key: composer-v1-{{ checksum "./server/composer.lock" }}
          paths: ./server/vendor
      - run: cd server/; npm ci
      - run: cd server/; npm run dev
      # - run: cd server/; php artisan migrate --force
      # - run: cd server/; php artisan db:seed --force
