version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/server

permissions:
  - object: /home/webapp/server
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: webapp
