version: 0.0
os: linux
files:
  - source: ../
    destination: /home/webapp/tp-ci

permissions:
  - object: /home/webapp/tp-ci
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: webapp
